# Generated by Django 4.0 on 2024-01-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipes_book.Ingredient'),
        ),
    ]
